#!/bin/bash

# Format all .c and .h files in the parser and fuzzer sources
echo "✨ Formatting .c and .h files"
find Sources Fuzzer -type f \( -name "*.c" -o -name "*.h" \) -exec clang-format -i "{}" +
if [ $? -eq 0 ]; then
  echo "✅ Formatting complete."
else
  echo "❌ Formatting failed!"
  exit 1
fi
