#!/bin/bash

xcodebuild \
  -scheme "$1" \
  -configuration Release \
  -sdk iphonesimulator \
  -destination "generic/platform=iOS Simulator,OS=$2" \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
  IPHONEOS_DEPLOYMENT_TARGET=15.0 \
  SKIP_INSTALL=NO \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGNING_ALLOWED=NO \
  clean build
