#!/bin/bash

xcodebuild \
  -scheme "$1" \
  -configuration Release \
  -sdk xrsimulator \
  -destination "generic/platform=visionOS Simulator,OS=$2" \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
  XROS_DEPLOYMENT_TARGET=1.0 \
  SKIP_INSTALL=NO \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGNING_ALLOWED=NO \
  clean build
