#!/bin/bash

swift package --allow-writing-to-directory docs \
    generate-documentation \
    --enable-experimental-combined-documentation \
    --target JBirdCore \
    --target JBirdMacros \
    --target JBirdBuilders \
    --disable-indexing \
    --transform-for-static-hosting \
    --hosting-base-path docs \
    --output-path docs