#!/bin/bash

xcodebuild \
  -scheme $1 \
  -configuration Release \
  -sdk macosx \
  -destination 'generic/platform=macOS' \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
  MACOSX_DEPLOYMENT_TARGET=12.0 \
  SKIP_INSTALL=NO \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGNING_ALLOWED=NO \
  clean build
