#!/bin/bash

xcodebuild \
  -scheme JBirdCore \
  -configuration Release \
  -sdk watchos \
  -destination 'generic/platform=watchOS' \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
  SKIP_INSTALL=NO \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGNING_ALLOWED=NO \
  clean build