#!/bin/bash

xcodebuild \
  -scheme "$1" \
  -configuration Release \
  -sdk watchsimulator \
  -destination "generic/platform=watchOS Simulator,OS=$2" \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
  WATCHOS_DEPLOYMENT_TARGET=8.0 \
  SKIP_INSTALL=NO \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGNING_ALLOWED=NO \
  clean build
