#!/bin/bash

cat > _config.yml <<EOF
remote_theme: vsanthanam/aviary@v0.2.0
plugins:
- jekyll-remote-theme
documentation_url: "https://www.usejbird.com/docs/documentation/jbird"
copyright_owner: "Varun Santhanam"
social_image: "https://www.usejbird.com/assets/images/social-image.png"
EOF

echo "✅ _config.yml created."