name: JBird CI
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - "main"
      - "*release*"
  pull_request:
    branches:
      - "main"
      - "*release*"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-ios-xcode:
    name: Build JBird (iOS)
    strategy:
      fail-fast: false
      matrix:
        scheme: ["JBird", "JBirdCore", "JBirdBuilders"]
        swift: ["6.2", "6.1"]
        version: ["26.0", "18.6", "17.7", "16.6", "15.7"]
        include:
          - swift: "6.2"
            runner: macos-26
            xcode: "26.0"
          - platform: "6.1"
            runner: macos-15
            xcode: "16.4"
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: ./.scripts/xcode-select ${{ matrix.xcode }}
    - name: Build ${{ matrix.scheme }} for iOS ${{ matrix.version }}
      run: ./.scripts/build-ios-xcode ${{ matrix.scheme }} ${{ matrix.version }}
  # build-xcode:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       platform: ['macos', 'maccatalyst', 'watchos', 'tvos', 'visionos']
  #       include:
  #         - platform: 'macos'
  #           name: 'macOS'
  #         - platform: 'maccatalyst'
  #           name: 'Mac Catalyst'
  #         - platform: 'ios'
  #           name: 'iOS'
  #         - platform: 'watchos'
  #           name: 'watchOS'
  #         - platform: 'tvos'
  #           name: 'tvOS'
  #         - platform: 'visionos'
  #           name: 'visionOS'
  #       scheme: [JBird, JBirdCore, JBirdBuilders]
  #   name: Build with Xcode (${{ matrix.scheme }}, ${{ matrix.name }})
  #   runs-on: macos-26
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #   - name: Select Xcode Version
  #     run: ./.scripts/xcode-select
  #   - name: Build ${{ matrix.scheme }} for ${{ matrix.name }}
  #     run: ./.scripts/build-${{ matrix.platform }}-xcode ${{ matrix.scheme }}
  swiftformat:
    name: Run SwiftFormat 
    runs-on: macos-26
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: ./.scripts/xcode-select
    - name: Lint with SwiftFormat
      run: ./.scripts/lint-swiftformat
  build-macos-spm:
    name: Build JBird (macOS)
    strategy:
      fail-fast: false
      matrix:
        swift: ['6.0', '6.1', '6.2']
        include:
          - swift: '6.0'
            runner: 'macos-15'
            xcode: '16.0'
          - swift: '6.1'
            runner: 'macos-15'
            xcode: '16.4'
          - swift: '6.2'
            runner: 'macos-26'
            xcode: '26.0'
    runs-on: ${{ matrix.runner }}
    outputs:
      artifact-name: macos-build
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: ./.scripts/xcode-select ${{ matrix.xcode }}
    - name: Build JBird
      run: swift build -v --build-tests --build-path .build
    - name: Compress Build
      run: zip -r build.zip .build
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: macos-build-${{ matrix.swift }}
        path: build.zip
  test-macos-spm:
    name: Test JBird (macOS)
    strategy:
      fail-fast: false
      matrix:
        swift: ['6.0', '6.1', '6.2']
        include:
          - swift: '6.0'
            runner: 'macos-15'
            xcode: '16.0'
          - swift: '6.1'
            runner: 'macos-15'
            xcode: '16.4'
          - swift: '6.2'
            runner: 'macos-26'
            xcode: '26.0'
    needs: build-macos-spm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Xcode Version
        run: ./.scripts/xcode-select ${{ matrix.xcode }}
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: macos-build-${{ matrix.swift }}
          path: .
      - name: Decompress Build
        run: unzip build.zip
      - name: Test JBird
        run: swift test --skip-build
  build-ubuntu-spm:
    name: Build JBird (Ubuntu)
    strategy:
      fail-fast: false
      matrix:
        swift: ['6.0', '6.1', '6.2']
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ubuntu-build
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build JBird
        run: swift build -v --build-tests --build-path .build
      - name: Install `zip`
        run: apt-get update && apt-get install -y zip
      - name: Compress Build
        run: zip -r build.zip .build
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build-${{ matrix.swift }}
          path: build.zip
  test-ubuntu-spm:
    name: Test JBird (Ubuntu)
    strategy:
      fail-fast: false
      matrix:
        swift: ['6.0', '6.1', '6.2']
    needs: build-ubuntu-spm
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-build-${{ matrix.swift }}
          path: .
      - name: Install `unzip`
        run: apt-get update && apt-get install -y unzip
      - name: Decompress Build
        run: unzip build.zip
      - name: Test JBird
        run: swift test --skip-build
  build-windows-spm:
    name: Build JBird (Windows)
    strategy:
      fail-fast: false
      matrix:
        swift: ['6.1', '6.2']
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Swift
        uses: compnerd/gha-setup-swift@main
        with:
          swift-version: swift-${{ matrix.swift }}-release
          swift-build: ${{ matrix.swift }}-RELEASE
      - name: Build JBird
        run: swift build -v --build-tests --disable-xctest --build-path .build -c debug -Xlinker /INCREMENTAL:NO
      - name: Compress Build
        shell: pwsh
        run: |
          Compress-Archive -Path ".build" -DestinationPath "build.zip" -Force
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-${{ matrix.swift }}
          path: build.zip
  test-windows-spm:
    name: Test JBird (Windows)
    strategy:
      fail-fast: false
      matrix:
        swift: ['6.1', '6.2']
    needs: build-windows-spm
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Swift
        uses: compnerd/gha-setup-swift@main
        with:
          swift-version: swift-${{ matrix.swift }}-release
          swift-build: ${{ matrix.swift }}-RELEASE
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: windows-build-${{ matrix.swift }}
          path: .
      - name: Decompress Build
        shell: pwsh
        run: |
          Expand-Archive -Path "build.zip" -DestinationPath "." -Force
      - name: Test JBird
        run: swift test --disable-xctest --skip-build
  build-wasm-spm:
    name: Build JBird (WASM)
    strategy:
      fail-fast: false
      matrix:
        swift: ['6.0.3', '6.1', '6.2']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - if: ${{ matrix.swift == '6.2' }}
        name: Setup Swift WASM (6.2)
        run: |
          swift sdk install https://download.swift.org/swift-6.2-release/wasm/swift-6.2-RELEASE/swift-6.2-RELEASE_wasm.artifactbundle.tar.gz \
            --checksum fe4e8648309fce86ea522e9e0d1dc48e82df6ba6e5743dbf0c53db8429fb5224
          swift sdk list
        # Important Note:
        # 
        # For 6.2 we're using the official toolchain since a lot of stuff from SwiftWasm has been upstreamed.
        # This is why the build scripts diverge -- we use SwiftWasm SDKs for < 6.2
        # Swift Testing also barely works on WASM (for now), so we're just going to build. No Tests.
      - if: ${{ matrix.swift != '6.2' }}
        name: Setup Swift WASM
        id: swiftwasm
        uses: swiftwasm/setup-swiftwasm@v2
        with:
          tag: swift-${{ matrix.swift }}-RELEASE 
      - if: ${{ matrix.swift == '6.2' }}
        name: Build JBird (6.2)
        run: swift build -v --swift-sdk swift-6.2-RELEASE_wasm --build-path .build
      - if: ${{ matrix.swift != '6.2' }}
        name: Build JBird
        run: swift build -v --swift-sdk ${{ steps.swiftwasm.outputs.swift-sdk-id }} --build-path .build
      - name: Install `zip`
        run: apt-get update && apt-get install -y zip
      - name: Compress Build
        run: zip -r build.zip .build
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build-${{ matrix.swift }}
          path: build.zip
  clang-format:
    name: Run clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Validate formatting
        run: ./.scripts/lint-clang-format
  lint-docc:
    name: Validate Documentation
    runs-on: macos-26
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: ./.scripts/xcode-select
    - name: Validate Documentation
      run: ./.scripts/lint-docc
  build-xcframework:
    strategy:
      fail-fast: false
      matrix:
        target: [JBird, JBirdCore, JBirdBuilders]
    name: Build XCFramework (${{ matrix.target }})
    runs-on: macos-26
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: ./.scripts/xcode-select
    - name: Build XCFramework
      run: ./.scripts/build-xcframework ${{ matrix.target }}
  coverage:
    name: Measure Test Coverage
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: ./.scripts/xcode-select
      - name: Run llvm-cov
        env:
          FAIL_ON_THRESHOLD: "true"
          COVERAGE_THRESHOLD: "80"
          REPORT_DIR: "coverage"
        run: .scripts/coverage
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.sha }}
          path: |
            coverage/
          if-no-files-found: error
          retention-days: 7
      - name: Upload to codecov.io
        if: ${{ always() }}
        uses: codecov/codecov-action@v4
        with:
          files: coverage/coverage.lcov
          flags: swiftpm,llvm-cov
          name: ${{ github.workflow }}-${{ github.run_id }}
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  static-analyzer:
    name: Run Static Analyzer
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: ./.scripts/xcode-select
      - name: Analyze C parsing core
        env:
          DERIVED_DATA: ${{ runner.temp }}/analyzer-derived-data
        run: |
          set -eo pipefail
          rm -rf "$DERIVED_DATA"
          xcodebuild \
            -project JBird.xcodeproj \
            -scheme JBirdParser \
            -configuration Debug \
            -destination 'platform=macOS' \
            -derivedDataPath "$DERIVED_DATA" \
            clean analyze
          rm -rf "$DERIVED_DATA"
  validate-pr:
    name: Validate Pull Request
    if: ${{ always() && github.event_name == 'pull_request' }}
    needs:
      # - build-xcode
      - build-ios-xcode
      - build-macos-spm
      - test-macos-spm
      - build-ubuntu-spm
      - test-ubuntu-spm
      - build-windows-spm
      - test-windows-spm
      - build-wasm-spm
      - build-xcframework
      - swiftformat
      - clang-format
      - lint-docc
      - coverage
      - static-analyzer
    runs-on: ubuntu-latest
    steps:
      - name: Check upstream jobs
        run: |
          # If any job failed, this status will not be 'success'
          if [[ "${{ needs.build-xcode.result }}" == "failure" ]] || \
            [[ "${{ needs.build-macos-spm.result }}" == "failure" ]] || \
            [[ "${{ needs.test-macos-spm.result }}" == "failure" ]] || \
            [[ "${{ needs.build-ubuntu-spm.result }}" == "failure" ]] || \
            [[ "${{ needs.test-ubuntu-spm.result }}" == "failure" ]] || \
            [[ "${{ needs.build-windows-spm.result }}" == "failure" ]] || \
            [[ "${{ needs.test-windows-spm.result }}" == "failure" ]] || \
            [[ "${{ needs.build-wasm-spm.result }}" == "failure" ]] || \
            [[ "${{ needs.build-xcframework.result }}" == "failure" ]] || \
            [[ "${{ needs.swiftformat.result }}" == "failure" ]] || \
            [[ "${{ needs.clang-format.result }}" == "failure" ]] || \
            [[ "${{ needs.lint-docc.result }}" == "failure" ]] || \
            [[ "${{ needs.coverage.result }}" == "failure" ]] || \
            [[ "${{ needs.static-analyzer.result }}" == "failure" ]]; then
            echo "❌ Upstream job failed."
            exit 1
          else
            echo "✅ All required jobs completed successfully."
          fi
