name: Build (Xcode Platforms)
permissions:
  contents: read
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-macos-xcode:
    strategy:
      matrix:
        platform: [macos, maccatalyst, ios, watchos, tvos, visionos]
    name: Build JBird (${{ matrix.platform }})
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: ./.scripts/xcode-select
    - name: Build JBird
      run: ./.scripts/build-${{ matrix.platform }}-xcode
